<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MenuItem;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ── MOMOS ──────────────────────────────────────────
            [
                'name'        => 'Classic Steamed Momos',
                'category'    => 'momos',
                'description' => 'Soft steamed dumplings with a flavourful vegetable filling — the way they\'re meant to be.',
                'price'       => 60.00,
                'emoji'       => '🥟',
                'badge'       => 'Bestseller',
                'badge_type'  => 'default',
                'tags'        => ['Steamed', 'Vegetarian'],
                'is_featured' => true,
                'sort_order'  => 1,
            ],
            [
                'name'        => 'Kurkure Momos',
                'category'    => 'momos',
                'description' => 'Crispy fried momos with an addictive crunch — the crowd favourite you can\'t stop eating.',
                'price'       => 80.00,
                'emoji'       => '🔥',
                'badge'       => 'Fan Favourite',
                'badge_type'  => 'fire',
                'tags'        => ['Fried', '#viral', 'Crispy'],
                'is_featured' => true,
                'sort_order'  => 2,
            ],
            [
                'name'        => 'Tandoori Momos',
                'category'    => 'momos',
                'description' => 'Smoky, spiced momos grilled to perfection with tandoori seasoning and mint chutney.',
                'price'       => 90.00,
                'emoji'       => '🍢',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Tandoori', 'Spicy'],
                'is_featured' => false,
                'sort_order'  => 3,
            ],
            [
                'name'        => 'Pan-Fried Momos',
                'category'    => 'momos',
                'description' => 'Golden crispy base, soft top — the best of both worlds in every bite.',
                'price'       => 80.00,
                'emoji'       => '🥟',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Pan-Fried', 'Crispy'],
                'is_featured' => false,
                'sort_order'  => 4,
            ],

            // ── BURGER ────────────────────────────────────────
            [
                'name'        => 'Classic Veggie Burger',
                'category'    => 'burger',
                'description' => 'Juicy veggie patty, fresh lettuce, tomatoes and our special sauce in a toasted sesame bun.',
                'price'       => 80.00,
                'emoji'       => '🍔',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Vegetarian', 'Grilled'],
                'is_featured' => false,
                'sort_order'  => 10,
            ],
            [
                'name'        => 'Spicy Aloo Burger',
                'category'    => 'burger',
                'description' => 'Crispy spiced potato patty with tangy sauces and crunchy veggies — a desi twist on a classic.',
                'price'       => 70.00,
                'emoji'       => '🍔',
                'badge'       => 'Popular',
                'badge_type'  => 'default',
                'tags'        => ['Spicy', 'Desi'],
                'is_featured' => true,
                'sort_order'  => 11,
            ],
            [
                'name'        => 'Double Smash Burger',
                'category'    => 'burger',
                'description' => 'Double patty, double cheese, double joy. Our biggest and boldest burger yet.',
                'price'       => 130.00,
                'emoji'       => '🍔',
                'badge'       => 'New',
                'badge_type'  => 'fire',
                'tags'        => ['Double', 'Cheesy', 'Hearty'],
                'is_featured' => true,
                'sort_order'  => 12,
            ],

            // ── SANDWICH ──────────────────────────────────────
            [
                'name'        => 'Grilled Veggie Sandwich',
                'category'    => 'sandwich',
                'description' => 'Freshly made sandwich loaded with veggies, sauces and cheese — the perfect quick bite.',
                'price'       => 70.00,
                'emoji'       => '🥪',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Fresh', 'Quick Bite'],
                'is_featured' => false,
                'sort_order'  => 20,
            ],
            [
                'name'        => 'Special Tuesday Sandwich',
                'category'    => 'sandwich',
                'description' => 'Our signature Tuesday special — loaded with layers of veggies, spread, and crispy crunch.',
                'price'       => 90.00,
                'emoji'       => '🥪',
                'badge'       => 'Tuesday Special',
                'badge_type'  => 'offer',
                'tags'        => ['Special', 'Loaded'],
                'is_featured' => true,
                'sort_order'  => 21,
            ],
            [
                'name'        => 'Club Sandwich',
                'category'    => 'sandwich',
                'description' => 'Triple-decker club sandwich with fresh veggies, cheese and our secret mayo spread.',
                'price'       => 100.00,
                'emoji'       => '🥪',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Triple-Decker', 'Cheesy'],
                'is_featured' => false,
                'sort_order'  => 22,
            ],

            // ── FRIES ─────────────────────────────────────────
            [
                'name'        => 'Bucket of Fries',
                'category'    => 'fries',
                'description' => 'Golden, crispy fries served by the bucket. Great to share, impossible to resist.',
                'price'       => 60.00,
                'emoji'       => '🍟',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Crispy', 'Shareable'],
                'is_featured' => false,
                'sort_order'  => 30,
            ],
            [
                'name'        => 'Masala Fries',
                'category'    => 'fries',
                'description' => 'Classic fries tossed in a spiced masala mix — addictive, bold and uniquely desi.',
                'price'       => 70.00,
                'emoji'       => '🍟',
                'badge'       => 'Spicy 🌶️',
                'badge_type'  => 'fire',
                'tags'        => ['Spicy', 'Masala', 'Desi'],
                'is_featured' => true,
                'sort_order'  => 31,
            ],
            [
                'name'        => 'Cheese Fries',
                'category'    => 'fries',
                'description' => 'Crispy fries smothered in melted cheese sauce. The ultimate comfort food.',
                'price'       => 80.00,
                'emoji'       => '🍟',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Cheesy', 'Comfort Food'],
                'is_featured' => false,
                'sort_order'  => 32,
            ],

            // ── NOODLES ───────────────────────────────────────
            [
                'name'        => 'Veg Chowmein',
                'category'    => 'noodles',
                'description' => 'Stir-fried noodles with fresh vegetables and soy-based sauce — fast, filling and flavourful.',
                'price'       => 70.00,
                'emoji'       => '🍜',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Stir-Fried', 'Vegetarian'],
                'is_featured' => false,
                'sort_order'  => 40,
            ],
            [
                'name'        => 'Spicy Schezwan Noodles',
                'category'    => 'noodles',
                'description' => 'Bold, fiery noodles tossed in Schezwan sauce with colourful veggies. Not for the faint-hearted!',
                'price'       => 80.00,
                'emoji'       => '🍜',
                'badge'       => 'Spicy 🔥',
                'badge_type'  => 'fire',
                'tags'        => ['Schezwan', 'Spicy', 'Bold'],
                'is_featured' => true,
                'sort_order'  => 41,
            ],

            // ── SHAKE ─────────────────────────────────────────
            [
                'name'        => 'Chocolate Shake',
                'category'    => 'shake',
                'description' => 'Rich, creamy chocolate milkshake topped with whipped cream. The perfect dessert sip.',
                'price'       => 80.00,
                'emoji'       => '🥤',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Chocolate', 'Sweet'],
                'is_featured' => false,
                'sort_order'  => 50,
            ],
            [
                'name'        => 'Vanilla Shake',
                'category'    => 'shake',
                'description' => 'Smooth and creamy vanilla shake — classic, comforting and always satisfying.',
                'price'       => 75.00,
                'emoji'       => '🥛',
                'badge'       => null,
                'badge_type'  => null,
                'tags'        => ['Vanilla', 'Classic'],
                'is_featured' => false,
                'sort_order'  => 51,
            ],
            [
                'name'        => 'Strawberry Shake',
                'category'    => 'shake',
                'description' => 'Fruity and refreshing strawberry milkshake — bright, sweet and utterly irresistible.',
                'price'       => 80.00,
                'emoji'       => '🍓',
                'badge'       => 'Popular',
                'badge_type'  => 'default',
                'tags'        => ['Strawberry', 'Fruity'],
                'is_featured' => true,
                'sort_order'  => 52,
            ],

            // ── KURKURE MOMOS (alias category for quickpick) ─
            [
                'name'        => 'Kurkure Momos (Large)',
                'category'    => 'kurkure momos',
                'description' => 'The same iconic Kurkure Momos but in a larger serving — perfect for sharing.',
                'price'       => 120.00,
                'emoji'       => '🔥',
                'badge'       => 'Large',
                'badge_type'  => 'fire',
                'tags'        => ['Fried', 'Crispy', 'Shareable'],
                'is_featured' => false,
                'sort_order'  => 5,
            ],
        ];

        foreach ($items as $item) {
            MenuItem::create($item);
        }
    }
}
